#pragma once
#include <string>
#include <map>
#include <set>

static std::set<std::string> s_commands  = {
	"BOUKI",
	"DROUB",
	"GOTOVA",
	"HLEB",
	"KNOTAUTHKA",
	"KRYSHA",
	"MAJIK",
	"MASUO",
	"MLEKO",
	"NIEUH",
	"NITZ",
	"OOSOUN",
	"OVOTCHEI",
	"POKASH",
	"POVIETZ",
	"PSHIPRAVA",
	"TACK",
	"RESET",
	"SER",
	"SUAVJIK",
	"VICKONAI",
	"VIEHPSHOVINA",
	"VITCISHTCH",
	"VODA",
	"VOUOVINA",
	"VROOTCH",
	"WAUCOTCHIA",
	"YAYA",
	"ZAKOOPEI",
	"ZAPISH",
};

static std::set<std::string> s_availableShoppingList = {
	"BULKI",
	"CHLEB",
	"DROB",
	"JAJA",
	"LAKOCIE",
	"MASLO",
	"MLEKO",
	"OWOCE",
	"PRZYPRAWA"
	"SER",
	"WIERZOWINA",
	"WODA",
	"WOLOWINA",
};

static std::map<std::string, std::string> s_stringPhonemsToStringConverter {
	{ "BOUKI",			"BULKI" 	},
	{ "DROUB",			"DROB"		},
	{ "GOTOVA",			"GOTOWE" 	},
	{ "HLEB",			"CHLEB"		},
	{ "KNOTAUTHKA",		"NOTATKA" 	},
	{ "KRYSHA",			"KRYSIA"	},
	{ "MAJIK",			"MADZIK"	},
	{ "MASUO",			"MASLO"		},
	{ "MLEKO",			"MLEKO" 	},
	{ "NIEUH",	"NIE"		},
	{ "NITZ",			"NIC" 		},
	{ "OOSOUN",         "USUN"		},
	{ "OVOTZE",			"OWOCE"		},
	{ "POKASH",			"POKAZ" 	},
	{ "POVIETZ",		"POWIEDZ" 	},
	{ "PSHIPRAVA",		"PRZYPRAWA" },
	{ "RESET",	        "RESET"		},
	{ "SER",			"SER"		},
	{ "SUAVJIK",		"SLAWDZIK" 	},
	{ "TACK",	"TAK"		},
	{ "VICKONAI",		"WYKONAJ" 	},
	{ "VIEHPSHOVINA",	"WIERZOWINA"},
	{ "VITCISHTCH",		"WYCZYSC"	},
	{ "VODA",			"WODA" 		},
	{ "VOUOVINA",		"WOLOWINA" 	},
	{ "VROOTCH",		"WROC" 		},
	{ "WAUCOTCHIA",		"LAKOCIE" 	},
	{ "YAYA",			"JAJA" 		},
	{ "ZAKOOPEI",		"ZAKUPY" 	},
	{ "ZAPISH",			"ZAPISZ"	} 
};
